controller:
  replicaCount: 3
  allowSnippetAnnotations: false
  service:
    externalTrafficPolicy: Local
  config:
    use-forwarded-headers: "true"
    server-tokens: "false"
    ssl-protocols: TLSv1.2 TLSv1.3
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/os: linux

  admissionWebhooks:
    patch:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "spot"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/os: linux
